classdef QPSKBitsGeneratorR < matlab.System
    properties (Nontunable)
        MessageLength = 112;
        BernoulliLength = 69;
        ScramblerBase = 2;
        ScramblerPolynomial = [1 1 1 0 1];
        ScramblerInitialConditions = [0 0 0 0];
    end

    properties (Access=private)
        pHeader
        pScrambler
        pMsgStrSet
        pCount
    end

    methods
        function obj = QPSKBitsGeneratorR(varargin)
            setProperties(obj,nargin,varargin{:});
        end
    end

    methods (Access=protected)
        function setupImpl(obj, ~)
            bbc = [+1, +1, +1, +1, +1, -1, -1, +1, +1, -1, +1, -1, +1, +1, +1, +1, +1, +1, -1, -1, +1, +1, -1, +1, -1, +1]; % Bipolar Barker Code
            ubc = ((bbc + 1) / 2)'; % Unipolar Barker Code
            temp = (repmat(ubc,1,2))';
            obj.pHeader = temp(:);
            obj.pCount = 0;
            obj.pScrambler = comm.Scrambler(obj.ScramblerBase, ...
            obj.ScramblerPolynomial, obj.ScramblerInitialConditions);
            obj.pMsgStrSet = ['Sun & Zhang 1000';...
                'Sun & Zhang 1001';...
                'Sun & Zhang 1002';...
                'Sun & Zhang 1003';...
                'Sun & Zhang 1004';...
                'Sun & Zhang 1005';...
                'Sun & Zhang 1006';...
                'Sun & Zhang 1007';...
                'Sun & Zhang 1008';...
                'Sun & Zhang 1009';...
                'Sun & Zhang 1010';...
                'Sun & Zhang 1011';...
                'Sun & Zhang 1012';...
                'Sun & Zhang 1013';...
                'Sun & Zhang 1014';...
                'Sun & Zhang 1015';...
                'Sun & Zhang 1016';...
                'Sun & Zhang 1017';...
                'Sun & Zhang 1018';...
                'Sun & Zhang 1019';...
                'Sun & Zhang 1020';...
                'Sun & Zhang 1021';...
                'Sun & Zhang 1022';...
                'Sun & Zhang 1023';...
                'Sun & Zhang 1024';...
                'Sun & Zhang 1025';...
                'Sun & Zhang 1026';...
                'Sun & Zhang 1027';...
                'Sun & Zhang 1028';...
                'Sun & Zhang 1029';...
                'Sun & Zhang 1030';...
                'Sun & Zhang 1031';...
                'Sun & Zhang 1032';...
                'Sun & Zhang 1033';...
                'Sun & Zhang 1034';...
                'Sun & Zhang 1035';...
                'Sun & Zhang 1036';...
                'Sun & Zhang 1037';...
                'Sun & Zhang 1038';...
                'Sun & Zhang 1039';...
                'Sun & Zhang 1040';...
                'Sun & Zhang 1041';...
                'Sun & Zhang 1042';...
                'Sun & Zhang 1043';...
                'Sun & Zhang 1044';...
                'Sun & Zhang 1045';...
                'Sun & Zhang 1046';...
                'Sun & Zhang 1047';...
                'Sun & Zhang 1048';...
                'Sun & Zhang 1049';...
                'Sun & Zhang 1050';...
                'Sun & Zhang 1051';...
                'Sun & Zhang 1052';...
                'Sun & Zhang 1053';...
                'Sun & Zhang 1054';...
                'Sun & Zhang 1055';...
                'Sun & Zhang 1056';...
                'Sun & Zhang 1057';...
                'Sun & Zhang 1058';...
                'Sun & Zhang 1059';...
                'Sun & Zhang 1060';...
                'Sun & Zhang 1061';...
                'Sun & Zhang 1062';...
                'Sun & Zhang 1063';...
                'Sun & Zhang 1064';...
                'Sun & Zhang 1065';...
                'Sun & Zhang 1066';...
                'Sun & Zhang 1067';...
                'Sun & Zhang 1068';...
                'Sun & Zhang 1069';...
                'Sun & Zhang 1070';...
                'Sun & Zhang 1071';...
                'Sun & Zhang 1072';...
                'Sun & Zhang 1073';...
                'Sun & Zhang 1074';...
                'Sun & Zhang 1075';...
                'Sun & Zhang 1076';...
                'Sun & Zhang 1077';...
                'Sun & Zhang 1078';...
                'Sun & Zhang 1079';...
                'Sun & Zhang 1080';...
                'Sun & Zhang 1081';...
                'Sun & Zhang 1082';...
                'Sun & Zhang 1083';...
                'Sun & Zhang 1084';...
                'Sun & Zhang 1085';...
                'Sun & Zhang 1086';...
                'Sun & Zhang 1087';...
                'Sun & Zhang 1088';...
                'Sun & Zhang 1089';...
                'Sun & Zhang 1090';...
                'Sun & Zhang 1091';...
                'Sun & Zhang 1092';...
                'Sun & Zhang 1093';...
                'Sun & Zhang 1094';...
                'Sun & Zhang 1095';...
                'Sun & Zhang 1096';...
                'Sun & Zhang 1097';...
                'Sun & Zhang 1098';...
                'Sun & Zhang 1099']; 
        end

        function [y,msg] = stepImpl(obj)
            % Converts the message string to bit format
            cycle = mod(obj.pCount,100);
            msgStr = obj.pMsgStrSet(cycle+1,:);
            msgBin = de2bi(int8(msgStr),7,'left-msb');
            msg = reshape(double(msgBin).',obj.MessageLength,1);
            data = [msg; randi([0 1], obj.BernoulliLength, 1)];

            % Scramble the data
            scrambledData = step(obj.pScrambler, data);

            % Append the scrambled bit sequence to the header
            y = [obj.pHeader ; scrambledData];

            obj.pCount = obj.pCount+1;
        end

        function resetImpl(obj)
            obj.pCount = 0;
            reset(obj.pScrambler);
        end

        function releaseImpl(obj)
            release(obj.pScrambler);
        end

        function N = getNumInputsImpl(~)
            N = 0; 
        end

        function N = getNumOutputsImpl(~)
            N = 2;
        end
    end
end